services:

  mirakc:
    build:
      context: mirakc
      dockerfile: public.Dockerfile
    container_name: mirakc
    init: true
    restart: unless-stopped
    devices:
      - /dev/bus:/dev/bus
      # チューナデバイスを指定する
      # - /dev/dvb:/dev/dvb
      # - /dev/pt3video0
      # - /dev/pt3video1
      # - /dev/pt3video2
      # - /dev/pt3video3
    # ports:
    #   - 40772:40772
    volumes:
      - mirakc-epg:/var/lib/mirakc/epg
      - ./mirakc/config.yml:/etc/mirakc/config.yml:ro
      - 
    environment:
      - TZ=Asia/Tokyo
      - RUST_LOG=info

  edcb:
    build:
      context: edcb
      # args:
      #   - EDCB_CHECKOUT=COMMIT_HASH_HERE
      #   - BON_DRIVER_CHECKOUT=COMMIT_HASH_HERE
      #   - EMWUI_CHECKOUT=COMMIT_HASH_HERE
    container_name: edcb
    restart: unless-stopped
    depends_on:
      - mirakc
    # devices:
    #   # for hardware transcoding
    #   - /dev/dri
    ports:
      - 5510:5510
    volumes:
      - ./edcb/ini:/var/local/edcb
      # 録画ファイルの保存先を指定する
      # - /mnt/recorded:/recorded
    # user: 1000:1000
    # group_add:
    #   # for hardware transcoding
    #   - video
    environment:
      - TZ=Asia/Tokyo
      - MIRAKC_ADDRESS=mirakc
      - MIRAKC_PORT=40772
      # - UMASK=002

  konomitv:
    image: konomitv
    container_name: KonomiTV
    build:
      context: KonomiTV
    restart: unless-stopped
    depends_on:
      - mirakc
    ports:
      - 7000:7000
    volumes:
      - type: bind
        source: './KonomiTV/config.yaml'
        target: '/code/config.yaml'
      - type: bind
        source: './KonomiTV/data/'
        target: '/code/server/data/'
      - type: bind
        source: './KonomiTV/logs/'
        target: '/code/server/logs/'
      - type: bind
        source: '/'
        target: '/host-rootfs/'
    # ==================== ↓↓↓↓↓ ここからユーザー設定 ↓↓↓↓↓ ====================
    # QSVEncC / VCEEncC を利用する (Intel Graphics / AMD GPU にアクセスする) ために必要な設定
    # VCEEncC (AMD GPU) を利用するには、別途 AMDGPU-PRO Driver のインストールが必要です。
    # GPU が1個も搭載されていない (/dev/dri/ 以下のデバイスファイルが存在しない) 特殊な環境では、
    # コメントアウトしてこの設定を無効にしないと、KonomiTV サーバーを起動できなくなります。

    devices:
      - '/dev/dri/:/dev/dri/'

    # NVEncC を利用する (NVIDIA GPU にアクセスする) ために必要な設定
    # NVEncC (NVIDIA GPU) を利用するには、別途 NVIDIA Graphics Driver と
    # NVIDIA Container Toolkit のインストールが必要です。
    # コメントアウトを解除してこの設定を有効にすると、NVIDIA GPU が搭載されていない環境では KonomiTV サーバーを起動できなくなります。

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [compute, utility, video]
    
    # ==================== ↑↑↑↑↑ ここまでユーザー設定 ↑↑↑↑↑ ====================

volumes:
  mirakc-epg:
    name: mirakc_epg
    driver: local
